### ISSUE TITLE
Restore Python API by separating Python API and CLI API functionality

### ISSUE THREAD

**Issue by matthewfeickert** [peterridolfi/Pyhf-to-Combine-converter#24]
There's a problem here though as the Python API isn't working as expected.

```console
[cmsusr@e619bd4fd100 Pyhf-to-Combine-converter]$ python3 docs/tutorial.py 
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "docs/tutorial.py", line 5, in <module>
    pyhf_converted_from_datacard.main(
TypeError: main() got an unexpected keyword argument 'outfile'
```

I forgot about this, but I think that what will be needed is to to refactor things so that:
* The `main` functions get renamed (e.g. Alex's suggestion of `pyhf_convert_to_datacard`)
* The `parser = OptionParser` stuff gets moved to a `main()` function which calls `pyhf_convert_to_datacard()` with the options passed as the required args. 

This separates out the Python API from the CLI API. This got broken when I was making the CLI API in PR #19.

This should probably get fixed in another PR before this goes in.

_Originally posted by @matthewfeickert in https://github.com/peterridolfi/Pyhf-to-Combine-converter/pull/22#discussion_r949464911_

**Comment by matthewfeickert** [comment]
@peterridolfi  I think I have a fix for this. PR incoming.
