### PR TITLE
add conversion tutorials

### LINKED ISSUE #13: Add example of conversion using files in repository for testing
There are some files in the repository that are kept for testing. To better document the API as well as give an example of conversion, add instructions on how to run a conversion using `pyhf_combine_converter`.

### LINKED ISSUE #14: Add test scripts for conversion
As a compliment to Issue #13, it would be great if there could be a test script under `tests`/ that adds a round-trip conversion, and to could be a runnable conversion test in general (which would be useful for things like Issue #7). Just ask if any part on this in particualr isn't clear! :+1:

### PR DESCRIPTION
**Pull request by peterridolfi**
* Resolves #13
* Resolves #14

### CODE REVIEW

File: docs/tutorial.md [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+```
+--out-datacard $DATACARD_FILE_NAME
+--shape-file $SHAPES_FILE_NAME
+```
+
+To run the translation in a python script, run the following code:
+
+```
+from pyhf_combine_converter import pyhf_convert_to_datacard
+pyhf_convert_to_datacard.main($JSON_FILE)
```
Comment (alexander-held) [inline docs/tutorial.md]: I am wondering now whether we should import `pyhf_convert_to_datacard.main` at the top level of the package and call it `pyhf_convert_to_datacard` to allow calling `pyhf_combine_converter.pyhf_convert_to_datacard()` directly, what do you think? (The downside of this is that the other functions inside `pyhf_convert_to_datacard` might not be easily accessible anymore then.)

File: docs/tutorial.md [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+```
+
+### Combine->pyhf
+
+To run the translation in the other direction, the protocols are very similar. However, if the model has shapes, meaning there are samples with multiple bins and a shapes file is designated in the datacard, this shapes file must be present in the directory from which you are running the command. Otherwise there will be an error that the shapes file was not found.
```
Comment (alexander-held) [inline docs/tutorial.md]: Since protocols have a technical meaning (https://peps.python.org/pep-0544/) in Python, maybe a word like "approach" or "method" or so could help avoid possible (though unlikely) confusion.

Comment (alexander-held) [inline docs/tutorial.md]: > this shapes file must be present in the directory from which you are running

Does the code currently not pick up files in subdirectories? For example if https://github.com/peterridolfi/Pyhf-to-Combine-converter/blob/070ca7b4fc525cf1ad46dbdfabd71b3dbaa8738a/test/multi_vs_single_bin/two_bin_datacard.txt#L4 was instead `folder/shapes.root` (and the file was in that subfolder `folder`), would that not work?

File: docs/tutorial.md [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+
+```
+--out-file $JSON_FILE_NAME
+```
+
+To run this conversion in a python script, run the following:
+
+```
+from pyhf_combine_converter import pyhf_converted_from_datacard
+pyhf_converted_from_datacard.main($DATACARD_FILE)
```
Comment (alexander-held) [inline docs/tutorial.md]: It might be convenient to return the dict with the specification from this function, such that a user can directly go on and use that dict without having to load it from a file first.

File: docs/tutorial.md (hunk 1 above)
Comment (matthewfeickert) [reply docs/tutorial.md]: Yeah, I think this is a good idea.

File: docs/tutorial.md [hunk 4]
```diff
@@ -0,0 +1,48 @@
+Once you are in an environment with both cvmfs commands and pyhf supported, as well as the package installed, you are ready to run the translation
+
+### pyhf->Combine
```
Comment (matthewfeickert) [inline docs/tutorial.md]:
```suggestion
### pyhf to Combine
```

Make the action text searchable.

File: docs/tutorial.md [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+```
+
+To run the translation in a python script, run the following code:
+
+```
+from pyhf_combine_converter import pyhf_convert_to_datacard
+pyhf_convert_to_datacard.main($JSON_FILE)
+```
+
+### Combine->pyhf
```
Comment (matthewfeickert) [inline docs/tutorial.md]:
```suggestion
### Combine to pyhf
```

Make the action text searchable.

File: docs/tutorial.py [hunk 6]
```diff
@@ -0,0 +1,7 @@
+import pyhf_combine_converter as converter
+
+##convert to pyhf
+converter.pyhf_converted_from_datacard.main("converted_datacard.txt", outfile = "pyhf_workspace.json")
+##convert back to datacard
+converter.pyhf_convert_to_datacard.main("pyhf_workspace.json", outdatacard = "combine_datacard.txt", shapefile = "shapes.root")
+
```
Comment (matthewfeickert) [inline docs/tutorial.py]:
```suggestion
from pyhf_combine_converter import pyhf_converted_from_datacard
from pyhf_combine_converter import pyhf_convert_to_datacard

##convert to pyhf
pyhf_converted_from_datacard.main(
    "converted_datacard.txt", outfile="pyhf_workspace.json"
)
##convert back to datacard
pyhf_convert_to_datacard.main(
    "pyhf_workspace.json", outdatacard="combine_datacard.txt", shapefile="shapes.root"
)
```

As no methods exist at import of `pyhf_combine_converter` (like Alex's point above) then need to import the files. This suggestion also runs Black on the file.

There's a problem here though as the Python API isn't working as expected.

```console
[cmsusr@e619bd4fd100 Pyhf-to-Combine-converter]$ python3 docs/tutorial.py 
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "docs/tutorial.py", line 5, in <module>
    pyhf_converted_from_datacard.main(
TypeError: main() got an unexpected keyword argument 'outfile'
```

I forgot about this, but I think that what will be needed is to to refactor things so that:
* The `main` functions get renamed (e.g. Alex's suggestion of `pyhf_convert_to_datacard`)
* The `parser = OptionParser` stuff gets moved to a `main()` function which calls `pyhf_convert_to_datacard()` with the options passed as the required args. 

block and if needed things can be put inside a `main` function still. This separates out the Python API from the CLI API. This got broken when I was making the CLI API in PR #19.

This should probably get fixed in another PR before this goes in.

**Review by matthewfeickert — CHANGES_REQUESTED** [review]

**Review by matthewfeickert — CHANGES_REQUESTED** [review]
Now that PR #25 is in, the tutorials should get updated to make sure they are compatible with the Python API (they mostly are).

Make sure the examples are runnable from the current state of the repository so that someone can literally just run the script and/or copy and paste code blocks.

Example: With the following contents in `docs/tutorial.py`

```python
# docs/tutorial.py
from pyhf_combine_converter import pyhf_converted_from_datacard
from pyhf_combine_converter import pyhf_convert_to_datacard

# convert to pyhf
pyhf_converted_from_datacard("converted_datacard.txt", outfile="pyhf_workspace.json")

# convert back to datacard
pyhf_convert_to_datacard(
    "pyhf_workspace.json", outdatacard="combine_datacard.txt", shapefile="shapes.root"
)
```

```console
[cmsusr@e619bd4fd100 Pyhf-to-Combine-converter]$ pwd
/home/cmsusr/CMSSW_11_2_0/workarea/Pyhf-to-Combine-converter
[cmsusr@e619bd4fd100 Pyhf-to-Combine-converter]$ python3 docs/tutorial.py 
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/cmsusr/.local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "docs/tutorial.py", line 5, in <module>
    pyhf_converted_from_datacard.pyhf_converted_from_datacard(
  File "/home/cmsusr/CMSSW_11_2_0/workarea/Pyhf-to-Combine-converter/src/pyhf_combine_converter/pyhf_converted_from_datacard.py", line 310, in pyhf_converted_from_datacard
    with open(input_datacard) as dc_file:
FileNotFoundError: [Errno 2] No such file or directory: 'converted_datacard.txt'
[cmsusr@e619bd4fd100 Pyhf-to-Combine-converter]$ 
```

So the tutorial needs to make clear _where_ the `converted_datacard.txt` is and or where the tutorial should be run from. Currently in the repo there is 

```console
[cmsusr@e619bd4fd100 Pyhf-to-Combine-converter]$ find . -type f -iname "converted_datacard.txt"
./test/big_model/converted_datacard.txt
./test/verification_model/converted_datacard.txt
```

File: docs/tutorial.md (hunk 1 above)
Comment (matthewfeickert) [reply docs/tutorial.md]: This was done in PR #28.

**Comment by matthewfeickert** [comment]
Rebased this PR to pickup changes from PR #29. Comments from before still apply and should be able to be carried forward. :+1:
